/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RegistroMarca;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sena
 */
public class FormConsultar extends javax.swing.JFrame {

    Conexion C = new Conexion();
    Connection cn =C.Conectar();        
    NumberFormat Moneda = NumberFormat.getCurrencyInstance();
    
    public FormConsultar() {
        initComponents();
        String titulos [] = {"Id","Nombre Marca","Productos","Fecha Registro","Valor"};
        DefaultTableModel tabla1= new DefaultTableModel(null, titulos); 
        TablaResult.setModel(tabla1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaResult = new javax.swing.JTable();
        Vr_Buscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rdb_marca = new javax.swing.JRadioButton();
        rdb_prods = new javax.swing.JRadioButton();
        btn_buscar = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setTitle("Consultar Marcas");
        jInternalFrame1.setToolTipText("");
        jInternalFrame1.setVisible(true);

        TablaResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TablaResult);

        jLabel2.setText("Buscar por:");

        jLabel1.setText("Valor a Buscar:");

        rdb_marca.setText("Nombre Marca");
        rdb_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_marcaActionPerformed(evt);
            }
        });

        rdb_prods.setText("Productos");
        rdb_prods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_prodsActionPerformed(evt);
            }
        });

        btn_buscar.setText("Buscar");
        btn_buscar.setName("BtnBuscar"); // NOI18N
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        BtnVolver.setText("Volver");
        BtnVolver.setName("BtnNuevo"); // NOI18N
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(rdb_marca)
                        .addGap(38, 38, 38)
                        .addComponent(rdb_prods)
                        .addGap(0, 92, Short.MAX_VALUE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(Vr_Buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_buscar)))
                .addContainerGap())
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rdb_marca)
                    .addComponent(rdb_prods))
                .addGap(17, 17, 17)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Vr_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_buscar))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdb_prodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_prodsActionPerformed
        rdb_marca.setSelected(false);
    }//GEN-LAST:event_rdb_prodsActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        
        String SQL ="";
        if(this.rdb_marca.isSelected()){
            SQL="SELECT idMarca,NombreMarca,Productos, FechaRegistro, Valor FROM marcas.marcas WHERE NombreMarca LIKE CONCAT('%',"+"?"+",'%');";
        }
        else if(this.rdb_prods.isSelected()){
            SQL="SELECT idMarca,NombreMarca,Productos, FechaRegistro, Valor FROM marcas.marcas WHERE Productos LIKE CONCAT('%',"+"?"+",'%');";
        }
        
        String titulos [] = {"Id","Nombre Marca","Productos","Fecha Registro","Valor"};
        DefaultTableModel tabla1= new DefaultTableModel(null, titulos); 
        TablaResult.setModel(tabla1);
        String valor=Vr_Buscar.getText();
        List<Marca> resultados=new ArrayList<Marca>();
        try{
            PreparedStatement pst = cn.prepareCall(SQL);
            pst.setString(1,valor);
            ResultSet RS= pst.executeQuery();
            while(RS.next()){
                resultados.add(new Marca(RS.getInt(1),RS.getString(2),RS.getString(3),RS.getDate(4),RS.getDouble(5)));
            }        
            
            for(Marca M:resultados){
                String[] registro = new String [5];
                registro[0] = String.valueOf(M.getIdMarca());
                registro[1] = M.getNombreMarca();
                registro[2] = M.getProductos();
                registro[3] = String.valueOf(M.getFechaRegistro());
                registro[4] = Moneda.format(M.getValor());
                tabla1.addRow(registro);
            }    
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", 0);
        }
        
     
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        this.setVisible(false);
        Inicio Home = new Inicio();
        Home.setVisible(true);
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void rdb_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_marcaActionPerformed
       rdb_prods.setSelected(false);
    }//GEN-LAST:event_rdb_marcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormConsultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVolver;
    private javax.swing.JTable TablaResult;
    private javax.swing.JTextField Vr_Buscar;
    public javax.swing.JButton btn_buscar;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JRadioButton rdb_marca;
    public javax.swing.JRadioButton rdb_prods;
    // End of variables declaration//GEN-END:variables
}
